# Generated by Django 3.1.1 on 2022-07-14 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20220714_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='user',
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='tracking',
            field=models.ManyToManyField(blank=True, related_name='tracked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
