# Generated by Django 3.1.1 on 2022-07-17 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_registereduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='liked',
            field=models.ManyToManyField(null=True, related_name='feed_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
